title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://mlsys-paper.github.io

aux_links:
  Template Repository: https://github.com/mlsys-paper/mlsys-paper.github.io
